version: '3.8'

services:
  backend:
    image: acrneospark.azurecr.io/ai-rag-foundation-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://backend:8000  # If backend needs this

  frontend:
    image: acrneospark.azurecr.io/ai-rag-foundation-frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000  # Make sure the frontend can reach the backend
